

logN_analysis:
	python3 logN_analysis.py --logN 16 --logQ 60 --logDelta 50 --library openfhe --stage encrypt_c0 --bitPerCoeff 64 --logSlots 15

logQ_analysis:
	python3 logQ_analysis.py --logDelta 50 --library openfhe --stage encrypt_c0 --bitPerCoeff 64

